# Site settings
title: kimtaesu
email: kimtaesoo188@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
email: kimtaesoo188@gmail.com
github_username:  kimtaesu

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems: ['jekyll-paginate', 'jekyll-mermaid', 'jekyll-assets', 'jekyll-toc']
paginate: 15
paginate_path: "/blog/page:num/"
mermaid:
  src: '/scripts/mermaid.js'

collections:
#  metal:
#    output: true
#    permalink: /metal/:path/
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/
  android:
    output: true
    permalink: /android/:path/
  python:
    output: true
    permalink: /python/:path/
  self-improvement:
    output: true
    permalink: /self-improvement/:path/

#poetry:
#    output: true
#    permalink: /poetry/:path/